version: '3.1'

services:
  mysql:
    image: mysql:8.0.28
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio_cep
    network_mode: "host"
    
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80

volumes:
  dbbase: