version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio_cep
    network_mode: "host"
